#----------------------------------------------------------------
# Travis-CI configuration for R packages
#
# REFERENCES:
# * Travis CI: https://docs.travis-ci.com/user/languages/r
# * covr: https://github.com/jimhester/covr
#
# YAML validated using http://www.yamllint.com/
#----------------------------------------------------------------
language: r
sudo: false
cache: packages
warnings_are_errors: false
r_check_args: --as-cran
latex: true

before_install:
  - tlmgr install bera
  - tlmgr install nowidow
  - tlmgr install parnotes
  - tlmgr install marginfix

matrix:
  include:
    - os: linux
      r: oldrel
    - os: linux
      r: release
    - os: linux
      r: devel
      env:
        - R_KEEP_PKG_SOURCE=yes
        - _R_S3_METHOD_LOOKUP_BASEENV_AFTER_GLOBALENV_=true
        - _R_S3_METHOD_LOOKUP_USE_TOPENV_AS_DEFENV_=true
        - _R_CHECK_CONNECTIONS_LEFT_OPEN_=true
        - _R_CHECK_LENGTH_1_CONDITION_=verbose
        - _R_CHECK_LENGTH_1_LOGIC2_=verbose
        - _R_CLASS_MATRIX_ARRAY_=true
    - os: osx
      r: oldrel
      r_build_args: --no-build-vignettes  ## WORKAROUND: sectsty.sty missing
      r_check_args: --as-cran --no-build-vignettes --no-vignettes
      before_install:
      env: NB='w/out vignettes' ## Just a label
    - os: osx
      r: release
      r_build_args: --no-build-vignettes  ## WORKAROUND: sectsty.sty missing
      r_check_args: --as-cran --no-build-vignettes --no-vignettes
      before_install:
      env: NB='w/out vignettes' ## Just a label
    - os: linux
      r: release
      r_check_args: --no-build-vignettes --no-codoc --no-examples --no-tests --no-manual --ignore-vignettes
      r_packages:
        - covr
      after_success:
        - Rscript -e 'covr::codecov(quiet=FALSE)'
      env: NB='w/ covr' ## Just a label
    
bioc_packages:
  - Biobase
  - CGHbase
  - CGHcall
  - DNAcopy
  - GenomicRanges
  - IRanges
  - Rsamtools
  - BiocStyle
  - BSgenome
  - GenomeInfoDb
  - QDNAseq.hg19
  - QDNAseq.mm10

notifications:
  email:
    on_success: change
    on_failure: change
